project:
  type: website

website:
  title: "Penarth Table Tennis Club"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - play.qmd
      - membership.qmd
      - shop.qmd
      - support.qmd
      - contact.qmd 
      - safeguarding.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



